export const WEBSITE_ROUTES = {
  home: "/",
  contacts: "/contacts",
  works: "/works",
  reviews: "/reviews",
  track: "/track/:token",
  priceList: "/price-list",
  warranty: "/warranty",
  about: "/about",
  emailVerify: "/auth/email-verify",
  confirmAccount: "/auth/confirm-account",
  confirmEmailChange: "/auth/confirm-email-change",
  resetPassword: "/auth/reset-password",
  googleCallback: "/auth/google/callback",
} as const;
